key_not_defined	This key is not defined.
null_tool	Ha, you just get a empty bottle, nothing has been changed:D
win_a_monster	You Just Win A Monster ouob
fence_hello	Hey, You just got a fence, you can use it to hit monsters(X)
balloon_hello	You got a balloon, as soon as you touch it, it broke and your attack has increased and nobody knows why.
backpack	Backpack
use_null_tool	You used a empty bottle and nothing happend:)
get_fence	You got a fence ouo
use_fence	You can now use fence to attack monsters;)
select_hello	Select an item from backpack using the id number of them or type [0] to exit: 
choice_invalid	This choice is not valid.
got_balloon	You got a balloon, use this to escape monsters(?).
bye	Bye~